### PR TITLE
Corrected ExtensionsForGenericArguments.GetAllProperties() extension method to return inherited property info once

### PR DESCRIPTION
**Pull request by Suremaker**
Example:
interface IBar {    float Float { get; set; }}
interface IBaz : IBar { double Double { get; set; } }
interface IFoo : IBaz { char Char { get; set; } }

Before fix, GetAllProperties() will return Float property twice for IFoo interface

### CODE REVIEW

**Comment by Suremaker** [comment]
I would add to this pull request that it is especially needed for proper messaging using RabbitMQ, otherwise the received dynamically implemented messages will contain duplicated properties (where only one of it will be populated with proper value).

**Comment by phatboyg** [comment]
Very interesting. Thanks I'll get it merged soon. 

---

Chris Patterson

**Comment by phatboyg** [comment]
done

**Comment by Suremaker** [comment]
Thank you! Can I ask when this fix will be available in NuGet ? 

Thanks,
Wojtek

**Comment by phatboyg** [comment]
The Magnum NuGet package was updated to 2.0.1. I forgot to bump the version in the MassTransit dependency list though. 

---

Chris Patterson

**Pull request closed without merging**
